/**
 * Splunk Processing Language (SPL) grammar for highlight.js
 *
 * Covers: pipe commands, eval/stats functions, boolean operators,
 * built-in fields, strings, numbers, and field=value assignments.
 */

/** @param {import('highlight.js').HLJSApi} hljs */
export default function splGrammar(hljs) {
    const COMMANDS = [
        'abstract',
        'accum',
        'addcoltotals',
        'addinfo',
        'addtotals',
        'anomalies',
        'anomalydetection',
        'anomalousvalue',
        'append',
        'appendcols',
        'appendpipe',
        'arules',
        'associate',
        'autoregress',
        'bin',
        'bucket',
        'bucketdir',
        'chart',
        'cluster',
        'cofilter',
        'collect',
        'concurrency',
        'contingency',
        'convert',
        'correlate',
        'datamodel',
        'dbinspect',
        'dedup',
        'delete',
        'delta',
        'diff',
        'erex',
        'eval',
        'eventcount',
        'eventstats',
        'extract',
        'fieldformat',
        'fields',
        'fieldsummary',
        'filldown',
        'fillnull',
        'findtypes',
        'foreach',
        'format',
        'from',
        'gauge',
        'gentimes',
        'geom',
        'geomfilter',
        'geostats',
        'head',
        'highlight',
        'history',
        'iconify',
        'inputcsv',
        'inputlookup',
        'iplocation',
        'join',
        'kmeans',
        'loadjob',
        'lookup',
        'makecontinuous',
        'makemv',
        'makeresults',
        'map',
        'metadata',
        'metasearch',
        'multikv',
        'multisearch',
        'mvcombine',
        'mvexpand',
        'noop',
        'nomv',
        'outlier',
        'outputcsv',
        'outputlookup',
        'outputtext',
        'pivot',
        'predict',
        'rangemap',
        'rare',
        'regex',
        'reltime',
        'rename',
        'replace',
        'rest',
        'return',
        'reverse',
        'rex',
        'run',
        'savedsearch',
        'scrub',
        'search',
        'searchtxn',
        'selfjoin',
        'sendemail',
        'set',
        'setfields',
        'sichart',
        'sirare',
        'sistats',
        'sitimechart',
        'sitop',
        'sort',
        'spath',
        'stats',
        'streamstats',
        'table',
        'tags',
        'tail',
        'timechart',
        'timewrap',
        'top',
        'transaction',
        'transpose',
        'trendline',
        'tstats',
        'typeahead',
        'typelearner',
        'typer',
        'uniq',
        'untable',
        'where',
        'xmlkv',
        'xmlunescape',
        'xpath',
        'xyseries',
    ];

    const EVAL_FUNCTIONS = [
        'abs',
        'acos',
        'acosh',
        'asin',
        'asinh',
        'atan',
        'atan2',
        'atanh',
        'case',
        'ceiling',
        'cidrmatch',
        'coalesce',
        'commands',
        'cos',
        'cosh',
        'exact',
        'exp',
        'floor',
        'hypot',
        'if',
        'in',
        'isbool',
        'isint',
        'isnotnull',
        'isnull',
        'isnum',
        'isstr',
        'len',
        'like',
        'ln',
        'log',
        'lower',
        'ltrim',
        'match',
        'max',
        'md5',
        'min',
        'mvappend',
        'mvcount',
        'mvdedup',
        'mvfilter',
        'mvfind',
        'mvindex',
        'mvjoin',
        'mvmap',
        'mvrange',
        'mvsort',
        'mvzip',
        'now',
        'null',
        'nullif',
        'pi',
        'pow',
        'printf',
        'random',
        'relative_time',
        'replace',
        'round',
        'rtrim',
        'searchmatch',
        'sha1',
        'sha256',
        'sha512',
        'sigfig',
        'sin',
        'sinh',
        'split',
        'sqrt',
        'strftime',
        'strptime',
        'substr',
        'tan',
        'tanh',
        'time',
        'tostring',
        'trim',
        'typeof',
        'upper',
        'urldecode',
        'validate',
    ];

    const STATS_FUNCTIONS = [
        'avg',
        'c',
        'count',
        'dc',
        'distinct_count',
        'earliest',
        'earliest_time',
        'estdc',
        'estdc_error',
        'exactperc',
        'first',
        'last',
        'latest',
        'latest_time',
        'list',
        'max',
        'mean',
        'median',
        'min',
        'mode',
        'p',
        'perc',
        'range',
        'rate',
        'rate_avg',
        'rate_sum',
        'stdev',
        'stdevp',
        'sum',
        'sumsq',
        'upperperc',
        'values',
        'var',
        'varp',
    ];

    // Deduplicate across eval and stats
    const ALL_FUNCTIONS = [...new Set([...EVAL_FUNCTIONS, ...STATS_FUNCTIONS])];

    const BUILTIN_FIELDS = [
        '_time',
        '_raw',
        '_indextime',
        '_cd',
        '_si',
        '_serial',
        'host',
        'source',
        'sourcetype',
        'index',
        'splunk_server',
        'linecount',
        'punct',
        'timeendpos',
        'timestartpos',
    ];

    const BOOLEAN_OPERATORS = ['AND', 'OR', 'NOT', 'IN', 'AS', 'BY', 'OVER', 'WHERE'];

    return {
        name: 'SPL',
        aliases: ['spl'],
        case_insensitive: true,
        contains: [
            // Pipe operator
            {
                scope: 'punctuation',
                match: /\|/,
            },
            // Field=value or field!=value assignments (highlight the field name)
            {
                scope: 'attr',
                match: /\b[a-zA-Z_][a-zA-Z0-9_.]*(?=\s*[!<>]?=)/,
            },
            // Boolean / keyword operators
            {
                scope: 'keyword',
                match: new RegExp(`\\b(${BOOLEAN_OPERATORS.join('|')})\\b`),
            },
            // Commands (first token after | or start of search)
            {
                scope: 'built_in',
                match: new RegExp(`\\b(${COMMANDS.join('|')})\\b`),
            },
            // Functions (followed by an opening paren)
            {
                scope: 'title.function',
                match: new RegExp(`\\b(${ALL_FUNCTIONS.join('|')})(?=\\s*\\()`),
            },
            // Built-in fields
            {
                scope: 'variable',
                match: new RegExp(`\\b(${BUILTIN_FIELDS.join('|')})\\b`),
            },
            // Double-quoted strings
            hljs.QUOTE_STRING_MODE,
            // Single-quoted strings
            {
                scope: 'string',
                begin: /'/,
                end: /'/,
                illegal: /\n/,
                contains: [hljs.BACKSLASH_ESCAPE],
            },
            // Backtick field names (e.g. `my field`)
            {
                scope: 'string',
                begin: /`/,
                end: /`/,
            },
            // Time modifiers: earliest=-15m, latest=now
            {
                scope: 'meta',
                match: /\b(earliest|latest)\s*=\s*[-+]?\d*[smhdwqy](@[smhdwqy])?/i,
            },
            // Numbers
            hljs.C_NUMBER_MODE,
            // Wildcards used in searches (e.g. error*)
            {
                scope: 'regexp',
                match: /\*+/,
            },
        ],
    };
}
